### ISSUE TITLE
링크가 안되는 이슈가 있습니다

### ISSUE THREAD

**Issue by J1min** [Lovingcats/Flutter_project#1]
안녕하세요 플러터 고수 조용제 개발자님
다름이 아니고 쉬스테마 링크를 눌러도 안가지는데 이거 프라이빗인 이슈인가요?? 궁금해요!!!

**Comment by Lovingcats** [comment]
헉!! 수정하겠습니다. 알려주셔서 감사합니다

**Comment by wonyongChoi05** [comment]
홍지민 잉인 개발자님 저 프로틴 통이랑 라켓 언제쯤 받으러 갈 수 있을까요??

**Comment by wonyongChoi05** [comment]
> 안녕하세요 플러터 고수 조용제 개발자님 다름이 아니고 쉬스테마 링크를 눌러도 안가지는데 이거 프라이빗인 이슈인가요?? 궁금해요!!!

홍지민 잉인 개발자님 저 프로틴 통이랑 라켓 언제쯤 받으러 갈 수 있을까요??

**Comment by J1min** [comment]
> 홍지민 잉인 개발자님 저 프로틴 통이랑 라켓 언제쯤 받으러 갈 수 있을까요??

저 내일 하단에 병원가러 가야하는데 그때 오시겠습니까
한 4시쯤? 일거같아요~

**Comment by wonyongChoi05** [comment]
> 저 내일 하단에 병원가러 가야하는데 그때 오시겠습니까 한 4시쯤? 일거같아요~

넵 알겠습니당 스카에서 짱박혀있다가 받으러 갈게용 톡주세용 잉 >< 인

**Comment by J1min** [comment]
넵 ~~
